Description: Create an ECR repository with a lifecycle policy.

Resources:
  MatchMakingEcr:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: match-making-repository
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep only the last 5 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 5
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
  
  PushToEcrUser:
    Type: AWS::IAM::User
    Properties:
      UserName: PushToEcrUser

  PushToEcrPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: 
              - "ecr:GetAuthorizationToken"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:InitiateLayerUpload"
              - "ecr:PutImage"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
            Resource: !GetAtt MatchMakingEcr.Arn
      PolicyName: PushToEcrPolicy
      Users:
           - !Ref PushToEcrUser
